name: Sten's CI/CD
run-name: "Sten's CI/CD"

on:
  push:

jobs:
  release:
    name: Release
    if: contains(github.event.head_commit.message, '.deploy')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [3.12]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@main

      - id: create_zip
        name: Create Zip File
        run: |
          cd Illyria
          VERSION=$(jq -r '.version.name' pack.mcmeta)
          zip -r "../Illyria_v$VERSION.zip" assets pack.mcmeta pack.png
        shell: bash

      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.create_zip.outputs.VERSION }}
        with:
          tag_name: ${{ steps.create_zip.outputs.VERSION }}
          files: Illyria_v${{ steps.create_zip.outputs.VERSION }}.zip
